import React from "react";
import { useI18n } from "../../hooks/useI18n.js";

/**
 * Item 42 — a payment receipt. Renders ONLY values actually returned or
 * generated by the real payment flow (processPayment() in
 * paymentService.js) — nothing here is invented or backfilled.
 */
export default function PaymentReceipt({ product, amount, asset, chain, recipient, transactionHash, status, simulated, occurredAt }) {
  const { t, locale } = useI18n();
  return (
    <div className="notice" style={{ textAlign: "left" }}>
      <span aria-hidden="true">{simulated ? "🧪" : "🧾"}</span>
      <span style={{ display: "grid", gap: 4, width: "100%" }}>
        <Row label={t("receipt.product")} value={product} />
        <Row label={t("receipt.amount")} value={`${amount} ${asset}`} />
        {chain && <Row label={t("pay.chain")} value={chain} />}
        <Row label={t("pay.recipient")} value={recipient} mono />
        <Row label={t("receipt.hash")} value={transactionHash} mono />
        <Row label={t("receipt.status")} value={status} />
        <Row label={t("receipt.datetime")} value={occurredAt ? new Date(occurredAt).toLocaleString(locale) : "—"} />
        {simulated && (
          <em style={{ marginTop: 2 }}>This is a simulated receipt. No blockchain transaction occurred.</em>
        )}
      </span>
    </div>
  );
}

function Row({ label, value, mono }) {
  return (
    <span className="flex justify-between gap-12">
      <span className="muted small">{label}</span>
      <span
        className="small strong"
        style={{ textAlign: "right", ...(mono ? { fontFamily: "monospace", fontSize: 12, wordBreak: "break-all" } : {}) }}
      >
        {value ?? "—"}
      </span>
    </span>
  );
}
