import React from "react";

/**
 * Item 42 — a payment receipt. Renders ONLY values actually returned or
 * generated by the real payment flow (processPayment() in
 * paymentService.js) — nothing here is invented or backfilled.
 */
export default function PaymentReceipt({ product, amount, asset, chain, recipient, transactionHash, status, simulated, occurredAt }) {
  return (
    <div className="notice" style={{ textAlign: "left" }}>
      <span aria-hidden="true">{simulated ? "🧪" : "🧾"}</span>
      <span style={{ display: "grid", gap: 4, width: "100%" }}>
        <Row label="Product" value={product} />
        <Row label="Amount" value={`${amount} ${asset}`} />
        {chain && <Row label="Chain" value={chain} />}
        <Row label="Recipient" value={recipient} mono />
        <Row label="Transaction hash" value={transactionHash} mono />
        <Row label="Status" value={status} />
        <Row label="Date/time" value={occurredAt ? new Date(occurredAt).toLocaleString() : "—"} />
        {simulated && (
          <em style={{ marginTop: 2 }}>This is a simulated receipt. No blockchain transaction occurred.</em>
        )}
      </span>
    </div>
  );
}

function Row({ label, value, mono }) {
  return (
    <span className="flex justify-between gap-12">
      <span className="muted small">{label}</span>
      <span
        className="small strong"
        style={{ textAlign: "right", ...(mono ? { fontFamily: "monospace", fontSize: 12, wordBreak: "break-all" } : {}) }}
      >
        {value ?? "—"}
      </span>
    </span>
  );
}
